In [1]:
import numpy as np
import pandas as pd
import random
from sklearn.svm import OneClassSVM
from sklearn.ensemble import IsolationForest

In [2]:
data_directory="/Users/poetofquality/Nutstore Files/Nutstore/Datasets/semi-conductor-image-classification-first/features"
# train_data = pd.read_csv(data_directory+"/train_pretrained_resnet50_features.csv", header = None)
train_data = pd.read_csv("train_pretrained_resnet50_features.csv", header = None)

In [5]:
# sample_size = 2600
# sample_ind = random.sample(range(0,train_data.shape[0]),sample_size);
sample_ind=range(0,train_data.shape[0])

In [6]:
train_x = np.array(train_data.iloc[sample_ind,2:])

In [7]:
iforest = IsolationForest(random_state=0,contamination=0.01).fit(train_x)

/usr/local/lib/python3.7/site-packages/sklearn/ensemble/iforest.py:247: FutureWarning: behaviour="old" is deprecated and will be removed in version 0.22. Please use behaviour="new", which makes the decision_function change to match other anomaly detection algorithm API.
  FutureWarning)


In [8]:
res_if = iforest.predict(train_x)

/usr/local/lib/python3.7/site-packages/sklearn/ensemble/iforest.py:415: DeprecationWarning: threshold_ attribute is deprecated in 0.20 and will be removed in 0.22.
  " be removed in 0.22.", DeprecationWarning)


In [9]:
np.unique(res_if, return_counts=True)

(array([-1,  1]), array([  270, 26697]))

In [22]:
norm_if_ind = np.where(res_if==1)

In [11]:
np.savetxt("norm_if_ind_1percent.csv", norm_if_ind)

In [12]:
ocsvm = OneClassSVM(nu=0.01).fit(train_x)

/usr/local/lib/python3.7/site-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


In [13]:
res = ocsvm.predict(train_x)

In [14]:
np.unique(res, return_counts=True)

(array([-1,  1]), array([  270, 26697]))

In [15]:
norm_ind = np.where(res==1)

In [19]:
np.savetxt("norm_ind_1percent.csv", norm_ind)

In [36]:
outlier_if_ind = np.where(res_if==-1)
outlier_ind = np.where(res==-1)

In [37]:
np.savetxt("outlier_if_ind.csv", outlier_if_ind)
np.savetxt("outlier_ind.csv", outlier_ind)

(array([   29,    64,   110,   112,   381,   428,   553,   570,   637,
          645,   815,   949,  1026,  1095,  1251,  1298,  1417,  1593,
         1597,  1721,  1725,  1750,  1853,  1861,  1926,  2108,  2238,
         2434,  2557,  2575,  2581,  2597,  2673,  2821,  2981,  3061,
         3156,  3261,  3279,  3366,  3545,  3674,  3702,  3759,  3768,
         3855,  3884,  4017,  4059,  4101,  4538,  4563,  4635,  4737,
         5071,  5097,  5285,  5327,  5328,  5470,  5616,  5630,  6328,
         6437,  6506,  6515,  6912,  6931,  6958,  7005,  7139,  7260,
         7311,  7382,  7519,  7529,  7582,  7615,  7738,  7816,  7919,
         7952,  8135,  8303,  8367,  8369,  8478,  8571,  8585,  8588,
         9163,  9164,  9182,  9400,  9449,  9493,  9535,  9652,  9849,
         9852, 10051, 10108, 10138, 10308, 10331, 10535, 10545, 10561,
        10822, 10936, 10996, 11106, 11254, 11295, 11328, 11386, 11683,
        11921, 11925, 11943, 12012, 12161, 12203, 12343, 12375, 12421,
      